=== kcomkar/betterbrowsers/com.sap.dcm.web.mobile/target/FOP_DCM_MOBILE_APPLICATION/WEB-INF/classes/ui/uiPage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sap.com/dcm/uiPage"
	xmlns:tns="http://www.sap.com/dcm/uiPage" elementFormDefault="qualified">
	
	<xs:complexType name="role">
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:complexType name="subPage">
		<xs:sequence > 
			<xs:element name="allowedRole" type="tns:role" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="uiText" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="page">
		<xs:sequence> 
			<xs:element name="page" type="tns:subPage" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="allowedRole" type="tns:role" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="defaultPage" type="xs:string" use="optional"/>
		<xs:attribute name="uiText" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:element name="pages">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="page" type="tns:page" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="defaultPage" type="xs:string" use="optional"/>
		</xs:complexType>
		
		<xs:keyref name="pageKeyRef" refer="tns:pageKey">
	      <xs:selector xpath=". | ./tns:page"/>
	      <xs:field xpath="@defaultPage"/>
	    </xs:keyref>
	    <xs:key name="pageKey">
	      <xs:selector xpath=".//tns:page"/>
	      <xs:field xpath="@id"/>
	    </xs:key>
	    		
		<xs:unique name="pageId">
		    <xs:selector xpath=".//tns:page"/>
		    <xs:field xpath="@tns:id"/>
		</xs:unique>
	</xs:element>
	
	
</xs:schema>

=== kcomkar/betterbrowsers/com.sap.dcm.web.mobile/target/FOP_DCM_MOBILE_APPLICATION/WEB-INF/classes/ui/uiPage.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:pages xmlns:ns="http://www.sap.com/dcm/uiPage"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sap.com/dcm/uiPage uiPage.xsd ">
	<ns:page id="com.sap.dcm.ilm" uiText="lbl.ilm.headPage">
		<ns:page id="com.sap.dcm.ilm.CustomerData" uiText="lbl.ilm.custData.headPage"/>
		<ns:allowedRole id="SAP_DCM_ILM_READ"/>
		<ns:allowedRole id="SAP_DCM_ILM_DELETE"/>
	</ns:page>
	<ns:page id="com.sap.dcm.appMgmt.AppMgmt" uiText="lbl.appMgmt.headPage">
		<ns:page id="com.sap.dcm.appMgmt.UserMgmt" uiText="lbl.appMgmt.userMgmt.headPage" />
		<ns:allowedRole id="SAP_DCM_USER_ADM"/>
	</ns:page>
</ns:pages>
